### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by mihha** [theterminalguy/floatcam#1]
Hi,

I saw your app intro on Reddit and I liked the idea behind it.

Since I am mainly Widows user, I was very excited when I saw that you mentioned in your README here on GitHub that there should be a Windows version on the release page, but I can't find it

Can you tell me do you plan to release a Windows version of your application, or did you make a mistake in the README?

Thank you in advance!

Regards,
Igor

**Comment by theterminalguy** [comment]
Hi @mihha 

I'll put up a windows version before the week runs out. Hopefully by today or latest tomorrow. If you have a windows machine, you can also build it yourself.

**Comment by mihha** [comment]
Thank you for the answer

To be honest, if I knew how to build it, I wouldn't be asking here for the Windows executable 🤔

**Comment by theterminalguy** [comment]
Hi @mihha 

I have made a release for windows. Thanks for the nudge. 

You can find the release [here ](https://github.com/theterminalguy/floatcam/releases/tag/v0.1.0-windows-beta)

**Comment by mihha** [comment]
Thank you for your effort

I will test the app and let you know if I find any bug or if I will have a suggestion for improvement
